/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/unclaim-fees/{protocol}/{chainId}': {
    /**
     * Batch get unclaimed fees
     * @deprecated
     */
    post: operations['postUnclaim-feesByProtocolByChainId']
  }
  '/cached/tokens/chart/{chainName}/rate': {
    /** Get token to token rate chart */
    get: operations['getCachedTokensChartByChainNameRate']
  }
  '/cached/tokens/chart/{chainName}/{address}/{protocol}/price': {
    /** Get token price chart by protocol */
    get: operations['getCachedTokensChartByChainNameByAddressByProtocolPrice']
  }
  '/cached/tokens/chart/{chainName}/{address}/price': {
    /** Get token price chart */
    get: operations['getCachedTokensChartByChainNameByAddressPrice']
  }
  '/cached/tokens/chart/{chainName}/{address}/{protocol}/volume': {
    /** Get token volume chart by protocol */
    get: operations['getCachedTokensChartByChainNameByAddressByProtocolVolume']
  }
  '/cached/tokens/chart/{chainName}/{address}/{protocol}/tvl': {
    /** Get token tvl chart by protocol */
    get: operations['getCachedTokensChartByChainNameByAddressByProtocolTvl']
  }
  '/cached/tokens/chart/{chainName}/{address}/tvl': {
    /** Get token tvl chart */
    get: operations['getCachedTokensChartByChainNameByAddressTvl']
  }
  '/cached/tokens/price/list/{ids}': {
    /** Get token price reference batch */
    get: operations['getCachedTokensPriceListByIds']
  }
  '/cached/tokens/{chainName}/{address}/price': {
    /**
     * Get token price reference
     * @description Get token price reference from liquidity pool. If more than one protocol is provided, it will return the largest TVL protocol
     */
    get: operations['getCachedTokensByChainNameByAddressPrice']
  }
  '/cached/tokens/extended/{chainName}/{address}': {
    /** Get extended token data */
    get: operations['getCachedTokensExtendedByChainNameByAddress']
  }
  '/cached/tokens/core/{chainName}/{address}': {
    /** Get core token data */
    get: operations['getCachedTokensCoreByChainNameByAddress']
  }
  '/cached/tokens/stable/{chainName}/{address}': {
    /** Get stable token data */
    get: operations['getCachedTokensStableByChainNameByAddress']
  }
  '/cached/tokens/extended/{chainName}/list/top': {
    /** Get extended top tokens */
    get: operations['getCachedTokensExtendedByChainNameListTop']
  }
  '/cached/tokens/core/{chainName}/list/top': {
    /** Get core top tokens */
    get: operations['getCachedTokensCoreByChainNameListTop']
  }
  '/cached/tokens/stable/{chainName}/list/top': {
    /** Get stable top tokens */
    get: operations['getCachedTokensStableByChainNameListTop']
  }
  '/cached/pools/ticks/extended/{chainName}/{pool}': {
    /** Get all ticks from extended pool */
    get: operations['getCachedPoolsTicksExtendedByChainNameByPool']
  }
  '/cached/pools/positions/extended/{chainName}/{pool}': {
    /** Get active positions from extended pool */
    get: operations['getCachedPoolsPositionsExtendedByChainNameByPool']
  }
  '/cached/pools/chart/extended/{chainName}/{address}/rate': {
    /** Get extended pool rate chart */
    get: operations['getCachedPoolsChartExtendedByChainNameByAddressRate']
  }
  '/cached/pools/chart/extended/{chainName}/{address}/fees': {
    /** Get extended pool fees chart */
    get: operations['getCachedPoolsChartExtendedByChainNameByAddressFees']
  }
  '/cached/pools/chart/{protocol}/{chainName}/{address}/tvl': {
    /** Get pool tvl chart */
    get: operations['getCachedPoolsChartByProtocolByChainNameByAddressTvl']
  }
  '/cached/pools/chart/{protocol}/{chainName}/{address}/volume': {
    /** Get pool volume chart */
    get: operations['getCachedPoolsChartByProtocolByChainNameByAddressVolume']
  }
  '/cached/pools/apr/core/{chainName}/{address}': {
    /** Get core lp apr */
    get: operations['getCachedPoolsAprCoreByChainNameByAddress']
  }
  '/cached/pools/apr/extended/{chainName}/{address}': {
    /** Get extended lp apr */
    get: operations['getCachedPoolsAprExtendedByChainNameByAddress']
  }
  '/cached/pools/apr/stable/{chainName}/{address}': {
    /** Get stable lp apr */
    get: operations['getCachedPoolsAprStableByChainNameByAddress']
  }
  '/cached/pools/apr/core/{chainName}/farms-lp': {
    /** Get core farm lp apr */
    get: operations['getCachedPoolsAprCoreByChainNameFarms-lp']
  }
  '/cached/pools/apr/extended/{chainName}/farms-lp': {
    /** Get extended farm lp apr */
    get: operations['getCachedPoolsAprExtendedByChainNameFarms-lp']
  }
  '/cached/pools/apr/stable/{chainName}/farms-lp': {
    /** Get stable farm lp apr */
    get: operations['getCachedPoolsAprStableByChainNameFarms-lp']
  }
  '/cached/pools/list': {
    /** Get pools list */
    get: operations['getCachedPoolsList']
  }
  '/cached/pools/extended/{chainName}/{address}': {
    /** Get extended pool data */
    get: operations['getCachedPoolsExtendedByChainNameByAddress']
  }
  '/cached/pools/core/{chainName}/{address}': {
    /** Get core pool data */
    get: operations['getCachedPoolsCoreByChainNameByAddress']
  }
  '/cached/pools/stable/{chainName}/{address}': {
    /** Get stable pool data */
    get: operations['getCachedPoolsStableByChainNameByAddress']
  }
  '/cached/pools/extended/{chainName}/list/simple': {
    /** Get simple extended pools list */
    get: operations['getCachedPoolsExtendedByChainNameListSimple']
  }
  '/cached/pools/extended/{chainName}/list/top': {
    /** Get top extended pools */
    get: operations['getCachedPoolsExtendedByChainNameListTop']
  }
  '/cached/pools/core/{chainName}/list/top': {
    /** Get top core pools */
    get: operations['getCachedPoolsCoreByChainNameListTop']
  }
  '/cached/pools/stable/{chainName}/list/top': {
    /** Get top stable pools */
    get: operations['getCachedPoolsStableByChainNameListTop']
  }
  '/cached/tx/extended/{chainName}/swaps': {
    /** Get extended swaps by page */
    get: operations['getCachedTxExtendedByChainNameSwaps']
  }
  '/cached/tx/extended/{chainName}/recent': {
    /** Get recent extended transaction */
    get: operations['getCachedTxExtendedByChainNameRecent']
  }
  '/cached/tx/core/{chainName}/recent': {
    /** Get recent core transaction */
    get: operations['getCachedTxCoreByChainNameRecent']
  }
  '/cached/tx/stable/{chainName}/recent': {
    /** Get recent stable transaction */
    get: operations['getCachedTxStableByChainNameRecent']
  }
  '/cached/block/{chainName}/{timestamp}': {
    /** Get closest block by unix timestamp */
    get: operations['getCachedBlockByChainNameByTimestamp']
  }
  '/cached/gauges/total-votes/all': {
    get: operations['getCachedGaugesTotal-votesAll']
  }
  '/cached/protocol/chart/{protocol}/{chainName}/volume': {
    /** Get protocol volume chart */
    get: operations['getCachedProtocolChartByProtocolByChainNameVolume']
  }
  '/cached/protocol/chart/{protocol}/{chainName}/tvl': {
    /** Get protocol tvl chart */
    get: operations['getCachedProtocolChartByProtocolByChainNameTvl']
  }
  '/cached/protocol/{protocol}/{chainName}/search': {
    /** Search protocol tokens and pools */
    get: operations['getCachedProtocolByProtocolByChainNameSearch']
  }
  '/cached/protocol/{protocol}/{chainName}/stats': {
    /** Get protocol stats */
    get: operations['getCachedProtocolByProtocolByChainNameStats']
  }
  '/status/{protocol}/{chainName}': {
    /** Get status of info data for chain */
    get: operations['getStatusByProtocolByChainName']
  }
  '/doc/json': {
    get: operations['getDocJson']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    /**
     * @description Chain name
     * @example arbitrum
     * @enum {string}
     */
    ChainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
    /**
     * @description Protocol version
     * @example extended
     * @enum {string}
     */
    Protocol: 'core' | 'extended' | 'stable'
    extendedTokenData: {
      /** @description Token address */
      id: string
      symbol: string
      name: string
      decimals: number
      totalTxCount: number
      txCount24h: number
      txCount48h: number
      txCount7d: number
      priceUSD: string
      priceUSD24h: string
      priceUSD48h: string
      priceUSD7d: string
      /** @description Total volume in USD */
      totalVolumeUSD: string
      volumeUSD24h: null | string
      volumeUSD48h: null | string
      volumeUSD7d: null | string
      tvlUSD: string
      tvlUSD24h: string
      tvlUSD48h: string
      tvlUSD7d: string
      tvl: string
      tvl24h: string
      tvl48h: string
      tvl7d: string
      totalFeeUSD: string
      feeUSD24h: string
      feeUSD48h: string
      feeUSD7d: string
    }
    coreTokenData: {
      /** @description Token address */
      id: string
      symbol: string
      name: string
      decimals: number
      totalTxCount: number
      txCount24h: number
      txCount48h: number
      txCount7d: number
      priceUSD: string
      priceUSD24h: string
      priceUSD48h: string
      priceUSD7d: string
      /** @description Total volume in USD */
      totalVolumeUSD: string
      volumeUSD24h: null | string
      volumeUSD48h: null | string
      volumeUSD7d: null | string
      tvlUSD: string
      tvlUSD24h: string
      tvlUSD48h: string
      tvlUSD7d: string
      tvl: string
      tvl24h: string
      tvl48h: string
      tvl7d: string
    }
    TokenPrice: {
      id: string
      priceUSD: string
      /**
       * @description Protocol version
       * @example extended
       * @enum {string}
       */
      protocol: 'core' | 'extended' | 'stable'
      tvlUSD: string
      timestamp: Record<string, never> | string
    }
    ticks: {
      /** @description Cursor for pagination start */
      startCursor?: string
      /** @description Cursor for pagination end */
      endCursor?: string
      /** @description Has next page */
      hasNextPage?: boolean
      /** @description Has previous page */
      hasPrevPage?: boolean
      rows: {
        id: string
        /** @description Tick index */
        tickIdx: number
        liquidityGross: string
        liquidityNet: string
        price0: string
        price1: string
      }[]
    }
    positions: {
      /** @description Cursor for pagination start */
      startCursor?: string
      /** @description Cursor for pagination end */
      endCursor?: string
      /** @description Has next page */
      hasNextPage?: boolean
      /** @description Has previous page */
      hasPrevPage?: boolean
      rows: {
        /** @description Position id */
        id: string
        liquidity: string
        /** @description Ethereum address */
        owner: string
        /** @description Lower tick index */
        lowerTickIdx: number
        /** @description Upper tick index */
        upperTickIdx: number
      }[]
    }
    /**
     * @description Chart period
     * @example 1D
     * @enum {string}
     */
    ChartPeriod: '1H' | '1D' | '1W' | '1M' | '1Y'
    transactions: {
      id: string
      transactionHash: string
      poolId: string
      token0: {
        id: string
        symbol: string
        name: string
        decimals: number
      }
      token1: {
        id: string
        symbol: string
        name: string
        decimals: number
      }
      amount0: string
      amount1: string
      amountUSD: string
      origin: null | string
      recipient: null | string
      timestamp: Record<string, never> | string
    }[]
    transactionsWithType: {
      /** @enum {string} */
      type: 'mint' | 'burn' | 'swap'
      id: string
      transactionHash: string
      poolId: string
      token0: {
        id: string
        symbol: string
        name: string
        decimals: number
      }
      token1: {
        id: string
        symbol: string
        name: string
        decimals: number
      }
      amount0: string
      amount1: string
      amountUSD: string
      origin: null | string
      recipient: null | string
      timestamp: Record<string, never> | string
    }[]
    ProtocolQuery: {
      /**
       * @description Chart group by
       * @example 1D
       * @enum {string}
       */
      groupBy: '1D' | '1W' | '1M'
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  /**
   * Batch get unclaimed fees
   * @deprecated
   */
  'postUnclaim-feesByProtocolByChainId': {
    parameters: {
      path: {
        protocol: 'plexswap-extended' | 'uniswap-extended'
        chainId: '1' | '56'
      }
    }
    requestBody: {
      content: {
        'application/json': {
          ids: string[]
        }
        'multipart/form-data': {
          ids: string[]
        }
        'text/plain': {
          ids: string[]
        }
      }
    }
    responses: {
      /** @description Successfully batch get unclaimed fees */
      200: {
        content: {
          'application/json': {
            data: {
              id: string
              token0: {
                symbol: string
                amount: string
                amountUSD: string
              }
              token1: {
                symbol: string
                amount: string
                amountUSD: string
              }
              totalUSD: string
            }[]
          }
          'multipart/form-data': {
            data: {
              id: string
              token0: {
                symbol: string
                amount: string
                amountUSD: string
              }
              token1: {
                symbol: string
                amount: string
                amountUSD: string
              }
              totalUSD: string
            }[]
          }
          'text/plain': {
            data: {
              id: string
              token0: {
                symbol: string
                amount: string
                amountUSD: string
              }
              token1: {
                symbol: string
                amount: string
                amountUSD: string
              }
              totalUSD: string
            }[]
          }
        }
      }
    }
  }
  /** Get token to token rate chart */
  getCachedTokensChartByChainNameRate: {
    parameters: {
      query: {
        /** @description Chart period */
        period: '1H' | '1D' | '1W' | '1M' | '1Y'
        /** @description Ethereum address */
        tokenA: string
        /** @description Ethereum address */
        tokenB: string
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            bucket: Record<string, never> | string
            open: null | string
            close: null | string
            high: null | string
            low: null | string
          }[]
        }
      }
    }
  }
  /** Get token price chart by protocol */
  getCachedTokensChartByChainNameByAddressByProtocolPrice: {
    parameters: {
      query: {
        /** @description Chart period */
        period: '1H' | '1D' | '1W' | '1M' | '1Y'
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Protocol version */
        protocol: 'core' | 'extended' | 'stable'
        /** @description Ethereum address */
        address: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            bucket: Record<string, never> | string
            open: null | string
            close: null | string
            high: null | string
            low: null | string
          }[]
        }
      }
    }
  }
  /** Get token price chart */
  getCachedTokensChartByChainNameByAddressPrice: {
    parameters: {
      query: {
        /** @description Chart period */
        period: '1H' | '1D' | '1W' | '1M' | '1Y'
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Ethereum address */
        address: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            bucket: Record<string, never> | string
            open: null | string
            close: null | string
            high: null | string
            low: null | string
          }[]
        }
      }
    }
  }
  /** Get token volume chart by protocol */
  getCachedTokensChartByChainNameByAddressByProtocolVolume: {
    parameters: {
      query: {
        /** @description Chart period */
        period: '1H' | '1D' | '1W' | '1M' | '1Y'
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Protocol version */
        protocol: 'core' | 'extended' | 'stable'
        /** @description Ethereum address */
        address: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            bucket: Record<string, never> | string
            volumeUSD: null | string
          }[]
        }
      }
    }
  }
  /** Get token tvl chart by protocol */
  getCachedTokensChartByChainNameByAddressByProtocolTvl: {
    parameters: {
      query: {
        /** @description Chart period */
        period: '1H' | '1D' | '1W' | '1M' | '1Y'
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Protocol version */
        protocol: 'core' | 'extended' | 'stable'
        /** @description Ethereum address */
        address: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            bucket: Record<string, never> | string
            tvlUSD: null | string
          }[]
        }
      }
    }
  }
  /** Get token tvl chart */
  getCachedTokensChartByChainNameByAddressTvl: {
    parameters: {
      query: {
        /** @description Chart period */
        period: '1H' | '1D' | '1W' | '1M' | '1Y'
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Ethereum address */
        address: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            bucket: Record<string, never> | string
            tvlUSD: null | string
          }[]
        }
      }
    }
  }
  /** Get token price reference batch */
  getCachedTokensPriceListByIds: {
    parameters: {
      path: {
        /** @description ids to query */
        ids: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': Record<string, never>
        }
      }
    }
  }
  /**
   * Get token price reference
   * @description Get token price reference from liquidity pool. If more than one protocol is provided, it will return the largest TVL protocol
   */
  getCachedTokensByChainNameByAddressPrice: {
    parameters: {
      query?: {
        timestamp?: string | number
        /** @description Array of protocol versions */
        protocols?: ('core' | 'extended' | 'stable') | ('core' | 'extended' | 'stable')[]
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Ethereum address */
        address: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['TokenPrice']
        }
      }
      400: {
        content: {
          'application/json': unknown
        }
      }
    }
  }
  /** Get extended token data */
  getCachedTokensExtendedByChainNameByAddress: {
    parameters: {
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Ethereum address */
        address: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['extendedTokenData']
        }
      }
    }
  }
  /** Get core token data */
  getCachedTokensCoreByChainNameByAddress: {
    parameters: {
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Ethereum address */
        address: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['coreTokenData']
        }
      }
    }
  }
  /** Get stable token data */
  getCachedTokensStableByChainNameByAddress: {
    parameters: {
      path: {
        chainName: 'bsc' | 'arbitrum'
        /** @description Ethereum address */
        address: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['coreTokenData']
        }
      }
    }
  }
  /** Get extended top tokens */
  getCachedTokensExtendedByChainNameListTop: {
    parameters: {
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            /** @description Token address */
            id: string
            symbol: string
            name: string
            decimals: number
            totalTxCount: number
            txCount24h: number
            txCount48h: number
            txCount7d: number
            priceUSD: string
            priceUSD24h: string
            priceUSD48h: string
            priceUSD7d: string
            /** @description Total volume in USD */
            totalVolumeUSD: string
            volumeUSD24h: null | string
            volumeUSD48h: null | string
            volumeUSD7d: null | string
            tvlUSD: string
            tvlUSD24h: string
            tvlUSD48h: string
            tvlUSD7d: string
            tvl: string
            tvl24h: string
            tvl48h: string
            tvl7d: string
            totalFeeUSD: string
            feeUSD24h: string
            feeUSD48h: string
            feeUSD7d: string
          }[]
        }
      }
    }
  }
  /** Get core top tokens */
  getCachedTokensCoreByChainNameListTop: {
    parameters: {
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            /** @description Token address */
            id: string
            symbol: string
            name: string
            decimals: number
            totalTxCount: number
            txCount24h: number
            txCount48h: number
            txCount7d: number
            priceUSD: string
            priceUSD24h: string
            priceUSD48h: string
            priceUSD7d: string
            /** @description Total volume in USD */
            totalVolumeUSD: string
            volumeUSD24h: null | string
            volumeUSD48h: null | string
            volumeUSD7d: null | string
            tvlUSD: string
            tvlUSD24h: string
            tvlUSD48h: string
            tvlUSD7d: string
            tvl: string
            tvl24h: string
            tvl48h: string
            tvl7d: string
          }[]
        }
      }
    }
  }
  /** Get stable top tokens */
  getCachedTokensStableByChainNameListTop: {
    parameters: {
      path: {
        chainName: 'bsc' | 'arbitrum'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            /** @description Token address */
            id: string
            symbol: string
            name: string
            decimals: number
            totalTxCount: number
            txCount24h: number
            txCount48h: number
            txCount7d: number
            priceUSD: string
            priceUSD24h: string
            priceUSD48h: string
            priceUSD7d: string
            /** @description Total volume in USD */
            totalVolumeUSD: string
            volumeUSD24h: null | string
            volumeUSD48h: null | string
            volumeUSD7d: null | string
            tvlUSD: string
            tvlUSD24h: string
            tvlUSD48h: string
            tvlUSD7d: string
            tvl: string
            tvl24h: string
            tvl48h: string
            tvl7d: string
          }[]
        }
      }
    }
  }
  /** Get all ticks from extended pool */
  getCachedPoolsTicksExtendedByChainNameByPool: {
    parameters: {
      query?: {
        /** @description Cursor for pagination before */
        before?: string
        /** @description Cursor for pagination after */
        after?: string
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Pool address */
        pool: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['ticks']
        }
      }
    }
  }
  /** Get active positions from extended pool */
  getCachedPoolsPositionsExtendedByChainNameByPool: {
    parameters: {
      query?: {
        /** @description Cursor for pagination before */
        before?: string
        /** @description Cursor for pagination after */
        after?: string
        /** @description Ethereum address */
        owner?: string
        tick?: string | number
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Pool address */
        pool: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['positions']
        }
      }
    }
  }
  /** Get extended pool rate chart */
  getCachedPoolsChartExtendedByChainNameByAddressRate: {
    parameters: {
      query: {
        /** @description Chart period */
        period: '1H' | '1D' | '1W' | '1M' | '1Y'
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Ethereum address */
        address: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            bucket: Record<string, never> | string
            open: null | string
            close: null | string
            high: null | string
            low: null | string
          }[]
        }
      }
    }
  }
  /** Get extended pool fees chart */
  getCachedPoolsChartExtendedByChainNameByAddressFees: {
    parameters: {
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Ethereum address */
        address: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            bucket: Record<string, never> | string
            feeUSD: string
          }[]
        }
      }
    }
  }
  /** Get pool tvl chart */
  getCachedPoolsChartByProtocolByChainNameByAddressTvl: {
    parameters: {
      query: {
        /** @description Chart period */
        period: '1H' | '1D' | '1W' | '1M' | '1Y'
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Protocol version */
        protocol: 'core' | 'extended' | 'stable'
        /** @description Ethereum address */
        address: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            bucket: Record<string, never> | string
            tvlUSD: null | string
          }[]
        }
      }
    }
  }
  /** Get pool volume chart */
  getCachedPoolsChartByProtocolByChainNameByAddressVolume: {
    parameters: {
      query: {
        /** @description Chart period */
        period: '1H' | '1D' | '1W' | '1M' | '1Y'
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Protocol version */
        protocol: 'core' | 'extended' | 'stable'
        /** @description Ethereum address */
        address: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            bucket: Record<string, never> | string
            volumeUSD: null | string
          }[]
        }
      }
    }
  }
  /** Get core lp apr */
  getCachedPoolsAprCoreByChainNameByAddress: {
    parameters: {
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Ethereum address */
        address: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            apr24h: string
            apr7d: string
            volumeUSD24h: string
            volumeUSD7d: string
          }
        }
      }
    }
  }
  /** Get extended lp apr */
  getCachedPoolsAprExtendedByChainNameByAddress: {
    parameters: {
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Ethereum address */
        address: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            apr24h: string
            apr7d: string
            volumeUSD24h: string
            volumeUSD7d: string
          }
        }
      }
    }
  }
  /** Get stable lp apr */
  getCachedPoolsAprStableByChainNameByAddress: {
    parameters: {
      path: {
        chainName: 'bsc' | 'arbitrum'
        /** @description Ethereum address */
        address: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            apr7d: string
            poolId: string
            virtualPrice: string
            virtualPrice7d: string
            volumeUSD7d: string
          }
        }
      }
    }
  }
  /** Get core farm lp apr */
  'getCachedPoolsAprCoreByChainNameFarms-lp': {
    parameters: {
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': Record<string, never>
        }
      }
    }
  }
  /** Get extended farm lp apr */
  'getCachedPoolsAprExtendedByChainNameFarms-lp': {
    parameters: {
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': Record<string, never>
        }
      }
    }
  }
  /** Get stable farm lp apr */
  'getCachedPoolsAprStableByChainNameFarms-lp': {
    parameters: {
      path: {
        chainName: 'bsc' | 'arbitrum'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': Record<string, never>
        }
      }
    }
  }
  /** Get pools list */
  getCachedPoolsList: {
    parameters: {
      query: {
        orderBy: 'tvlUSD' | 'volumeUSD24h' | 'apr24h' | 'volumeUSD7d'
        /** @description Array of protocol versions */
        protocols: ('core' | 'extended' | 'stable') | ('core' | 'extended' | 'stable')[]
        /** @description Array of chain names */
        chains:
          | ('bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum')
          | ('bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum')[]
        /** @description Filter by Pool address, should be use with chain filter */
        pool?: string
        /** @description Filter by token address, should be use with chain filter */
        token?: string
        /** @description Cursor for pagination before */
        before?: string
        /** @description Cursor for pagination after */
        after?: string
      }
    }
    responses: {
      200: {
        content: never
      }
    }
  }
  /** Get extended pool data */
  getCachedPoolsExtendedByChainNameByAddress: {
    parameters: {
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Ethereum address */
        address: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            /** @description Pool id */
            id: string
            token0: {
              id: string
              symbol: string
              name: string
              decimals: number
            }
            token1: {
              id: string
              symbol: string
              name: string
              decimals: number
            }
            /** @description Total volume in USD */
            totalVolumeUSD: string
            /** @description Token0 price to token1 */
            token0Price: string
            /** @description Token1 price to token0 */
            token1Price: string
            /** @description Total value locked in token0 */
            tvlToken0: string
            /** @description Total value locked in token1 */
            tvlToken1: string
            /** @description Volume in USD in 24h */
            volumeUSD24h: string
            /** @description Volume in USD in 24h */
            volumeUSD48h: string
            /** @description Volume in USD in 7d */
            volumeUSD7d: string
            /** @description Total value locked in USD */
            tvlUSD: string
            /** @description Total value locked in USD 24h ago */
            tvlUSD24h: string
            /** @description Total value locked in USD 24h ago */
            tvlUSD48h: string
            /** @description Total value locked in USD 7d ago */
            tvlUSD7d: string
            /** @description Pool created at timestamp */
            createdAtTimestamp: Record<string, never> | string
            feeTier: number
            liquidity: string
            sqrtPrice: string
            tick: null | number
            /** @description Total fee in USD */
            totalFeeUSD: string
            /** @description Fee in USD in 24h */
            feeUSD24h: string
            /** @description Fee in USD in 24h */
            feeUSD48h: string
            /** @description Fee in USD in 7d */
            feeUSD7d: string
            /** @description Total protocol fee in USD */
            totalProtocolFeeUSD: string
            /** @description Protocol fee in USD in 24h */
            protocolFeeUSD24h: string
            /** @description Protocol fee in USD in 24h */
            protocolFeeUSD48h: string
            /** @description Protocol fee in USD in 7d */
            protocolFeeUSD7d: string
          }
        }
      }
    }
  }
  /** Get core pool data */
  getCachedPoolsCoreByChainNameByAddress: {
    parameters: {
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Ethereum address */
        address: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            /** @description Pool id */
            id: string
            token0: {
              id: string
              symbol: string
              name: string
              decimals: number
            }
            token1: {
              id: string
              symbol: string
              name: string
              decimals: number
            }
            /** @description Total volume in USD */
            totalVolumeUSD: string
            /** @description Token0 price to token1 */
            token0Price: string
            /** @description Token1 price to token0 */
            token1Price: string
            /** @description Total value locked in token0 */
            tvlToken0: string
            /** @description Total value locked in token1 */
            tvlToken1: string
            /** @description Volume in USD in 24h */
            volumeUSD24h: string
            /** @description Volume in USD in 24h */
            volumeUSD48h: string
            /** @description Volume in USD in 7d */
            volumeUSD7d: string
            /** @description Total value locked in USD */
            tvlUSD: string
            /** @description Total value locked in USD 24h ago */
            tvlUSD24h: string
            /** @description Total value locked in USD 24h ago */
            tvlUSD48h: string
            /** @description Total value locked in USD 7d ago */
            tvlUSD7d: string
            /** @description Pool created at timestamp */
            createdAtTimestamp: Record<string, never> | string
          }
        }
      }
    }
  }
  /** Get stable pool data */
  getCachedPoolsStableByChainNameByAddress: {
    parameters: {
      path: {
        chainName: 'bsc' | 'arbitrum'
        /** @description Ethereum address */
        address: string
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            /** @description Pool id */
            id: string
            token0: {
              id: string
              symbol: string
              name: string
              decimals: number
            }
            token1: {
              id: string
              symbol: string
              name: string
              decimals: number
            }
            /** @description Total volume in USD */
            totalVolumeUSD: string
            /** @description Token0 price to token1 */
            token0Price: string
            /** @description Token1 price to token0 */
            token1Price: string
            /** @description Total value locked in token0 */
            tvlToken0: string
            /** @description Total value locked in token1 */
            tvlToken1: string
            /** @description Volume in USD in 24h */
            volumeUSD24h: string
            /** @description Volume in USD in 24h */
            volumeUSD48h: string
            /** @description Volume in USD in 7d */
            volumeUSD7d: string
            /** @description Total value locked in USD */
            tvlUSD: string
            /** @description Total value locked in USD 24h ago */
            tvlUSD24h: string
            /** @description Total value locked in USD 24h ago */
            tvlUSD48h: string
            /** @description Total value locked in USD 7d ago */
            tvlUSD7d: string
            /** @description Pool created at timestamp */
            createdAtTimestamp: Record<string, never> | string
            lpAddress: string
            virtualPrice: string
            virtualPrice24h: null | string
            virtualPrice48h: null | string
            virtualPrice7d: null | string
          }
        }
      }
    }
  }
  /** Get simple extended pools list */
  getCachedPoolsExtendedByChainNameListSimple: {
    parameters: {
      query?: {
        /** @description Filter by Token0 address */
        token0?: string
        /** @description Filter by Token1 address */
        token1?: string
        /** @description Cursor for pagination before */
        before?: string
        /** @description Cursor for pagination after */
        after?: string
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            /** @description Cursor for pagination start */
            startCursor?: string
            /** @description Cursor for pagination end */
            endCursor?: string
            /** @description Has next page */
            hasNextPage?: boolean
            /** @description Has previous page */
            hasPrevPage?: boolean
            rows: {
              id: string
              feeTier: number
              token0: {
                id: string
                symbol: string
                name: string
                decimals: number
              }
              token1: {
                id: string
                symbol: string
                name: string
                decimals: number
              }
              totalVolumeUSD: string
              tvlUSD: string
              tvlToken0: string
              tvlToken1: string
            }[]
          }
        }
      }
    }
  }
  /** Get top extended pools */
  getCachedPoolsExtendedByChainNameListTop: {
    parameters: {
      query?: {
        /** @description Filter by Token address */
        token?: string
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            /** @description Pool id */
            id: string
            token0: {
              id: string
              symbol: string
              name: string
              decimals: number
            }
            token1: {
              id: string
              symbol: string
              name: string
              decimals: number
            }
            /** @description Total volume in USD */
            totalVolumeUSD: string
            /** @description Token0 price to token1 */
            token0Price: string
            /** @description Token1 price to token0 */
            token1Price: string
            /** @description Total value locked in token0 */
            tvlToken0: string
            /** @description Total value locked in token1 */
            tvlToken1: string
            /** @description Volume in USD in 24h */
            volumeUSD24h: string
            /** @description Volume in USD in 24h */
            volumeUSD48h: string
            /** @description Volume in USD in 7d */
            volumeUSD7d: string
            /** @description Total value locked in USD */
            tvlUSD: string
            /** @description Total value locked in USD 24h ago */
            tvlUSD24h: string
            /** @description Total value locked in USD 24h ago */
            tvlUSD48h: string
            /** @description Total value locked in USD 7d ago */
            tvlUSD7d: string
            /** @description Pool created at timestamp */
            createdAtTimestamp: Record<string, never> | string
            feeTier: number
            liquidity: string
            sqrtPrice: string
            tick: null | number
            /** @description Total fee in USD */
            totalFeeUSD: string
            /** @description Fee in USD in 24h */
            feeUSD24h: string
            /** @description Fee in USD in 24h */
            feeUSD48h: string
            /** @description Fee in USD in 7d */
            feeUSD7d: string
            /** @description Total protocol fee in USD */
            totalProtocolFeeUSD: string
            /** @description Protocol fee in USD in 24h */
            protocolFeeUSD24h: string
            /** @description Protocol fee in USD in 24h */
            protocolFeeUSD48h: string
            /** @description Protocol fee in USD in 7d */
            protocolFeeUSD7d: string
          }[]
        }
      }
    }
  }
  /** Get top core pools */
  getCachedPoolsCoreByChainNameListTop: {
    parameters: {
      query?: {
        /** @description Filter by Token address */
        token?: string
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            /** @description Pool id */
            id: string
            token0: {
              id: string
              symbol: string
              name: string
              decimals: number
            }
            token1: {
              id: string
              symbol: string
              name: string
              decimals: number
            }
            /** @description Total volume in USD */
            totalVolumeUSD: string
            /** @description Token0 price to token1 */
            token0Price: string
            /** @description Token1 price to token0 */
            token1Price: string
            /** @description Total value locked in token0 */
            tvlToken0: string
            /** @description Total value locked in token1 */
            tvlToken1: string
            /** @description Volume in USD in 24h */
            volumeUSD24h: string
            /** @description Volume in USD in 24h */
            volumeUSD48h: string
            /** @description Volume in USD in 7d */
            volumeUSD7d: string
            /** @description Total value locked in USD */
            tvlUSD: string
            /** @description Total value locked in USD 24h ago */
            tvlUSD24h: string
            /** @description Total value locked in USD 24h ago */
            tvlUSD48h: string
            /** @description Total value locked in USD 7d ago */
            tvlUSD7d: string
            /** @description Pool created at timestamp */
            createdAtTimestamp: Record<string, never> | string
          }[]
        }
      }
    }
  }
  /** Get top stable pools */
  getCachedPoolsStableByChainNameListTop: {
    parameters: {
      query?: {
        /** @description Filter by Token address */
        token?: string
      }
      path: {
        chainName: 'bsc' | 'arbitrum'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            /** @description Pool id */
            id: string
            token0: {
              id: string
              symbol: string
              name: string
              decimals: number
            }
            token1: {
              id: string
              symbol: string
              name: string
              decimals: number
            }
            /** @description Total volume in USD */
            totalVolumeUSD: string
            /** @description Token0 price to token1 */
            token0Price: string
            /** @description Token1 price to token0 */
            token1Price: string
            /** @description Total value locked in token0 */
            tvlToken0: string
            /** @description Total value locked in token1 */
            tvlToken1: string
            /** @description Volume in USD in 24h */
            volumeUSD24h: string
            /** @description Volume in USD in 24h */
            volumeUSD48h: string
            /** @description Volume in USD in 7d */
            volumeUSD7d: string
            /** @description Total value locked in USD */
            tvlUSD: string
            /** @description Total value locked in USD 24h ago */
            tvlUSD24h: string
            /** @description Total value locked in USD 24h ago */
            tvlUSD48h: string
            /** @description Total value locked in USD 7d ago */
            tvlUSD7d: string
            /** @description Pool created at timestamp */
            createdAtTimestamp: Record<string, never> | string
            lpAddress: string
            virtualPrice: string
            virtualPrice24h: null | string
            virtualPrice48h: null | string
            virtualPrice7d: null | string
          }[]
        }
      }
    }
  }
  /** Get extended swaps by page */
  getCachedTxExtendedByChainNameSwaps: {
    parameters: {
      query?: {
        /** @description Filter by token address */
        token?: string
        /** @description Filter by pool address */
        pool?: string
        /** @description Cursor for pagination before */
        before?: string
        /** @description Cursor for pagination after */
        after?: string
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            /** @description Cursor for pagination start */
            startCursor?: string
            /** @description Cursor for pagination end */
            endCursor?: string
            /** @description Has next page */
            hasNextPage?: boolean
            /** @description Has previous page */
            hasPrevPage?: boolean
            rows: {
              id: string
              transactionHash: string
              poolId: string
              token0: {
                id: string
                symbol: string
                name: string
                decimals: number
              }
              token1: {
                id: string
                symbol: string
                name: string
                decimals: number
              }
              amount0: string
              amount1: string
              amountUSD: string
              origin: null | string
              recipient: null | string
              timestamp: Record<string, never> | string
            }[]
          }
          'multipart/form-data': {
            /** @description Cursor for pagination start */
            startCursor?: string
            /** @description Cursor for pagination end */
            endCursor?: string
            /** @description Has next page */
            hasNextPage?: boolean
            /** @description Has previous page */
            hasPrevPage?: boolean
            rows: {
              id: string
              transactionHash: string
              poolId: string
              token0: {
                id: string
                symbol: string
                name: string
                decimals: number
              }
              token1: {
                id: string
                symbol: string
                name: string
                decimals: number
              }
              amount0: string
              amount1: string
              amountUSD: string
              origin: null | string
              recipient: null | string
              timestamp: Record<string, never> | string
            }[]
          }
          'text/plain': {
            /** @description Cursor for pagination start */
            startCursor?: string
            /** @description Cursor for pagination end */
            endCursor?: string
            /** @description Has next page */
            hasNextPage?: boolean
            /** @description Has previous page */
            hasPrevPage?: boolean
            rows: {
              id: string
              transactionHash: string
              poolId: string
              token0: {
                id: string
                symbol: string
                name: string
                decimals: number
              }
              token1: {
                id: string
                symbol: string
                name: string
                decimals: number
              }
              amount0: string
              amount1: string
              amountUSD: string
              origin: null | string
              recipient: null | string
              timestamp: Record<string, never> | string
            }[]
          }
        }
      }
    }
  }
  /** Get recent extended transaction */
  getCachedTxExtendedByChainNameRecent: {
    parameters: {
      query?: {
        /** @description Filter by token address */
        token?: string
        /** @description Filter by pool address */
        pool?: string
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['transactionsWithType']
        }
      }
    }
  }
  /** Get recent core transaction */
  getCachedTxCoreByChainNameRecent: {
    parameters: {
      query?: {
        /** @description Filter by token address */
        token?: string
        /** @description Filter by pool address */
        pool?: string
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['transactionsWithType']
        }
      }
    }
  }
  /** Get recent stable transaction */
  getCachedTxStableByChainNameRecent: {
    parameters: {
      query?: {
        /** @description Filter by token address */
        token?: string
        /** @description Filter by pool address */
        pool?: string
      }
      path: {
        chainName: 'bsc' | 'arbitrum'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['transactionsWithType']
        }
      }
    }
  }
  /** Get closest block by unix timestamp */
  getCachedBlockByChainNameByTimestamp: {
    parameters: {
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        timestamp: string | number
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            /** @example 11150916 */
            height: number
            /** @example 1603964988 */
            timestamp: number
          }
        }
      }
      400: {
        content: {
          'application/json': unknown
        }
      }
    }
  }
  'getCachedGaugesTotal-votesAll': {
    responses: {
      200: {
        content: {
          'application/json': {
            epoch: number
            totalWeight?: string
          }[]
        }
      }
    }
  }
  /** Get protocol volume chart */
  getCachedProtocolChartByProtocolByChainNameVolume: {
    parameters: {
      query: {
        /** @description Chart group by */
        groupBy: '1D' | '1W' | '1M'
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Protocol version */
        protocol: 'core' | 'extended' | 'stable'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            bucket: Record<string, never> | string
            volumeUSD: null | string
          }[]
        }
      }
    }
  }
  /** Get protocol tvl chart */
  getCachedProtocolChartByProtocolByChainNameTvl: {
    parameters: {
      query: {
        /** @description Chart group by */
        groupBy: '1D' | '1W' | '1M'
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Protocol version */
        protocol: 'core' | 'extended' | 'stable'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            bucket: Record<string, never> | string
            tvlUSD: null | string
          }[]
        }
      }
    }
  }
  /** Search protocol tokens and pools */
  getCachedProtocolByProtocolByChainNameSearch: {
    parameters: {
      query: {
        text: string
      }
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Protocol version */
        protocol: 'core' | 'extended' | 'stable'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            tokens: {
              id: string
              name: string
              symbol: string
              decimals: number
              priceUSD: string
              totalVolumeUSD: string
              tvlUSD: string
              tvl: string
              totalTxCount: number
            }[]
            pools: {
              id: string
              token0: {
                id: string
                symbol: string
                name: string
                decimals: number
              }
              token1: {
                id: string
                symbol: string
                name: string
                decimals: number
              }
              feeTier: number
              tvlUSD: string
              totalVolumeUSD: string
              tvlToken0: string
              tvlToken1: string
            }[]
          }
        }
      }
    }
  }
  /** Get protocol stats */
  getCachedProtocolByProtocolByChainNameStats: {
    parameters: {
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Protocol version */
        protocol: 'core' | 'extended' | 'stable'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            tvlUSD: string
            totalVolumeUSD: string
            totalProtocolFeeUSD: string
            totalProtocolFeeUSD24h: string
            totalProtocolFeeUSD48h: string
            totalProtocolFeeUSD30d: string
            totalTxCount: number
            totalFeeUSD: string
            totalFeeUSD24h: string
            totalFeeUSD48h: string
            totalFeeUSD30d: string
            tvlUSD24h: string
            tvlUSD48h: string
            tvlUSD30d: string
            volumeUSD24h: string
            volumeUSD48h: string
            volumeUSD30d: string
            txCount24h: number
            txCount48h: number
            txCount30d: number
          }
        }
      }
    }
  }
  /** Get status of info data for chain */
  getStatusByProtocolByChainName: {
    parameters: {
      path: {
        /** @description Chain name */
        chainName: 'bsc' | 'ethereum' | 'base' | 'opbnb' | 'zksync' | 'polygon-zkevm' | 'linea' | 'arbitrum'
        /** @description Protocol version */
        protocol: 'core' | 'extended' | 'stable'
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            height: number
          }
          'multipart/form-data': {
            height: number
          }
          'text/plain': {
            height: number
          }
        }
      }
    }
  }
  getDocJson: {
    responses: {
      200: {
        content: never
      }
    }
  }
}
